// 8-bit 像素图标矩阵：'X' = currentColor，'.' = 磷光绿
export const MATRICES = {
  chip: [
    '               ',
    '               ',
    '  XXXXXXXXX    ',
    ' XX       XX   ',
    '  X XXXXX X    ',
    ' XX X   X XX   ',
    '  X X . X X    ',
    ' XX X   X XX   ',
    '  X XXXXX X    ',
    ' XX       XX   ',
    '  XXXXXXXXX    ',
    '               ',
    '               ',
    '               ',
    '               ',
  ],
  terminal: [
    '               ',
    '               ',
    ' XXXXXXXXXXXXX ',
    ' X. . .      X ',
    ' XXXXXXXXXXXXX ',
    ' X X         X ',
    ' XX          X ',
    ' X X ...     X ',
    ' X           X ',
    ' X           X ',
    ' XXXXXXXXXXXXX ',
    '               ',
    '               ',
    '               ',
    '               ',
  ],
  keyboard: [
    '               ',
    '               ',
    '               ',
    ' XXXXXXXXXXXXX ',
    ' XX X X X X XX ',
    ' XXXXXXXXXXXXX ',
    ' XX X X X X XX ',
    ' XXXXXXXXXXXXX ',
    '   XXXXXXXXX   ',
    ' XXXXXXXXXXXXX ',
    '               ',
    '               ',
    '               ',
    '               ',
    '               ',
  ],
  coffee: [
    '               ',
    '      .        ',
    '    .   .      ',
    '               ',
    '   XXXXXXXXX   ',
    '   X       X X ',
    '   X       XXX ',
    '   X       X X ',
    '   XXXXXXXXX   ',
    '               ',
    '  XXXXXXXXXXX  ',
    '               ',
    '               ',
    '               ',
    '               ',
  ],
  board: [
    '               ',
    '               ',
    ' XXXXXXXXXXXXX ',
    ' X .     .   X ',
    ' X X     X   X ',
    ' X X     X   X ',
    ' X XXXXXXX   X ',
    ' X       X   X ',
    ' X .     X . X ',
    ' X X     X X X ',
    ' XXXXXXXXXXXXX ',
    '               ',
    '               ',
    '               ',
    '               ',
  ],
  led: [
    '    .   .      ',
    '  .         .  ',
    '     XXXXX     ',
    '    XXXXXXX    ',
    '    XXX.XXX    ',
    '    XXXXXXX    ',
    '     XXXXX     ',
    '       X       ',
    '       X       ',
    '      X X      ',
    '     X   X     ',
    '    X     X    ',
    '               ',
    '               ',
    '               ',
  ],
} as const;

export type IconName = keyof typeof MATRICES;